### ISSUE TITLE
Feature ability to set variables for specific media query

### ISSUE THREAD

**Issue by fgdaniel** [mertasan/tailwindcss-variables#116]
I would like it, and I don't think that I would only like it, to have the ability to insert variables for different resolutions (media query) directly from tailwind.config.js, to be able to use the function @screen or simply @media in the following way: ( Note already works but does not set to :root level)

```javascript
const defColors = require("tailwindcss/colors");
module.exports = {
	theme: {
		variables: (theme) => ({
			// default variables on all devices
			DEFAULT: {
				white: defColors.white,
			},
			// override variables on certain media query, can use @screen md|lg|xl or @media (min|max-width: value)
			"@screen md": {
				white: 'red',
			}
		}),

	},

};
```

Example below how it already works and is wrong

```css
:root {
    --colors-white: #fff;
    --colors-white-rgb: 255,255,255;
}

@media (min-width: 768px) {
    --colors-white:red
}
```

If we look, it does not set at the level of :root {}

Below is an example of how it should be

```css
:root {
    --colors-white: #fff;
    --colors-white-rgb: 255,255,255;
}

@media (min-width: 768px) {
    :root {
        --colors-white:red
    }
}
```

Thank you and I'm sorry that I don't have code as an example by which we can achieve this aspect, it's beyond my powers
