### ISSUE TITLE
Issues with text/bg opacity?

### ISSUE THREAD

**Issue by captenmasin** [mertasan/tailwindcss-variables#2]
### Versions:
- Package Version: 1.0.3
- Tailwindcss Version: 2.1.1

### Question:
I'm not sure if this would even be possible with how Tailwind as a whole is setup to work, but basically when using this plugin it will create a CSS variable like so 

```css
--colors-primary: #7868e6;
```

Which is great, but when using in conjunction with anything related to opacity it doesn't respect that at all

For example
```html
<div class="bg-primary bg-opacity-50"></div>
```
Doesn't have a background opacity of 50

Of course this could (theoretically) be fixed in userland by setting the variable in tailwindconfig.js like so

```js
colors: {
	primary: {
		DEFAULT: 'var(--colors-primary), var(--tw-bg-opacity)'
	},
}
```

But then this won't text into account the `text-opacity` classes

Has anyone managed to figure this out?

**Comment by mertasan** [comment]
@captenmasin please upgrade the plugin to `v1.1.0`

73a0596edf197506dc975847c5770baafdb7509a

```js
// tailwind.config.js

const colorVariable = require('@mertasan/tailwindcss-variables/colorVariable')

module.exports = {
  theme: {
    colors: {
      primary: colorVariable('--colors-primary'),
      secondary: colorVariable('var(--colors-secondary)'), // or
      gray: 'var(--colors-gray)', // or default usage
    },
    variables: {
      DEFAULT: {
        colors: {
          primary: '#ffffff',
          secondary: '#000000',
          gray: '#6B7280'
        },
      },
      },
    },
  },
  plugins: [
    require('@mertasan/tailwindcss-variables')
  ]
}
```

**output:**

```css
:root {
   --colors-primary: #ffffff;
   --colors-secondary: #000000;
   --colors-gray: #6B7280
}

.text-primary {
  --tw-text-opacity: 1;
  color: rgba(var(--colors-primary), var(--tw-text-opacity))
}

.bg-secondary {
  --tw-bg-opacity: 1;
  background-color: rgba(var(--colors-secondary), var(--tw-bg-opacity))
}

.bg-gray {
  background-color: var(--colors-gray)
}
```

**Comment by mertasan** [comment]
https://github.com/mertasan/tailwindcss-variables/blob/73a0596edf197506dc975847c5770baafdb7509a/__tests__/color-variable-helper.test.js#L37-L63

**Comment by captenmasin** [comment]
It worked!
Thank you I appreciate the help

One thing I noticed is variables must be set like so
```
const primary = '120, 104, 230'
const secondary = '120, 104, 230'
const tertiary = '228, 251, 255'
```

As wrapping them in rgb() like `rgb(228, 251, 255)` would result in the CSS being read as:
```
.bg-tertiary {
    --tw-bg-opacity: 1;
	background-color: rgba(rgb(228, 251, 255), 1);
}
```
Which, of course, isn't valid

**Comment by captenmasin** [comment]
Hex values in the variables also don't work as will output
```
rgba(#e4fbff, 1)
```

Which also isn't valid

**Comment by mertasan** [comment]
I have new ideas on this. The new version will be released within a few hours 👍

**Comment by mertasan** [comment]
```javascript
plugins: [
  require('@mertasan/tailwindcss-variables'){
    colorVariables: true
  }
]
````

**Example**

```javascript
// tailwind.config.js

const colorVariable = require('@mertasan/tailwindcss-variables/colorVariable')

module.exports = {
  theme: {
    colors: {
      primary: colorVariable('--colors-primary'),
      secondary: colorVariable('var(--colors-secondary)'), // or
      gray: 'var(--colors-gray)', // or default usage
    },
    variables: {
      DEFAULT: {
        colors: {
          primary: '#ff0',
          secondary: '#000000',
          gray: '#6B7280'
        },
      },
      },
    },
  },
  plugins: [
    require('@mertasan/tailwindcss-variables'){
      colorVariables: true
    }
  ]
}
```

**Output:**

```css
:root {
  --colors-primary: #ff0;
  --colors-secondary: #000000;
  --colors-gray: #6B7280;
  --colors-primary-rgb: 255,255,0;
  --colors-secondary-rgb: 0,0,0;
  --colors-gray-rgb: 107,114,128
}

.text-primary {
  --tw-text-opacity: 1;
  color: rgba(var(--colors-primary-rgb), var(--tw-text-opacity))
}

.bg-secondary {
  --tw-bg-opacity: 1;
  background-color: rgba(var(--colors-secondary-rgb), var(--tw-bg-opacity))
}

.bg-gray {
  background-color: var(--colors-gray)
}
```
